sudo: required
services:
	- docker

before_install:
	- docker build -t wentai9899/docker-react -f Dockerfile.dev . 

script:
	- docker run -e CI=true wentai9899/docker-react npm run test
	# 123123212321